// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: mab.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecisionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CampaignId     string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	UserContext    string                 `protobuf:"bytes,2,opt,name=user_context,json=userContext,proto3" json:"user_context,omitempty"`
	AvailableAdIds []string               `protobuf:"bytes,3,rep,name=available_ad_ids,json=availableAdIds,proto3" json:"available_ad_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	mi := &file_mab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_mab_proto_rawDescGZIP(), []int{0}
}

func (x *DecisionRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *DecisionRequest) GetUserContext() string {
	if x != nil {
		return x.UserContext
	}
	return ""
}

func (x *DecisionRequest) GetAvailableAdIds() []string {
	if x != nil {
		return x.AvailableAdIds
	}
	return nil
}

type DecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SelectedAdId  string                 `protobuf:"bytes,1,opt,name=selected_ad_id,json=selectedAdId,proto3" json:"selected_ad_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	mi := &file_mab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_mab_proto_rawDescGZIP(), []int{1}
}

func (x *DecisionResponse) GetSelectedAdId() string {
	if x != nil {
		return x.SelectedAdId
	}
	return ""
}

type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	AdId          string                 `protobuf:"bytes,2,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_mab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_mab_proto_rawDescGZIP(), []int{2}
}

func (x *EventRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *EventRequest) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

func (x *EventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_mab_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mab_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_mab_proto_rawDescGZIP(), []int{3}
}

func (x *EventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Impressions   map[string]int32       `protobuf:"bytes,1,rep,name=impressions,proto3" json:"impressions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Clicks        map[string]int32       `protobuf:"bytes,2,rep,name=clicks,proto3" json:"clicks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_mab_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mab_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_mab_proto_rawDescGZIP(), []int{4}
}

func (x *SyncRequest) GetImpressions() map[string]int32 {
	if x != nil {
		return x.Impressions
	}
	return nil
}

func (x *SyncRequest) GetClicks() map[string]int32 {
	if x != nil {
		return x.Clicks
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_mab_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mab_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_mab_proto_rawDescGZIP(), []int{5}
}

func (x *SyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mab_proto protoreflect.FileDescriptor

const file_mab_proto_rawDesc = "" +
	"\n" +
	"\tmab.proto\x12\x03mab\"\x7f\n" +
	"\x0fDecisionRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12!\n" +
	"\fuser_context\x18\x02 \x01(\tR\vuserContext\x12(\n" +
	"\x10available_ad_ids\x18\x03 \x03(\tR\x0eavailableAdIds\"8\n" +
	"\x10DecisionResponse\x12$\n" +
	"\x0eselected_ad_id\x18\x01 \x01(\tR\fselectedAdId\"c\n" +
	"\fEventRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x13\n" +
	"\x05ad_id\x18\x02 \x01(\tR\x04adId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\")\n" +
	"\rEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x83\x02\n" +
	"\vSyncRequest\x12C\n" +
	"\vimpressions\x18\x01 \x03(\v2!.mab.SyncRequest.ImpressionsEntryR\vimpressions\x124\n" +
	"\x06clicks\x18\x02 \x03(\v2\x1c.mab.SyncRequest.ClicksEntryR\x06clicks\x1a>\n" +
	"\x10ImpressionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a9\n" +
	"\vClicksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"B\n" +
	"\fSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xad\x01\n" +
	"\tMabEngine\x128\n" +
	"\tGetNextAd\x12\x14.mab.DecisionRequest\x1a\x15.mab.DecisionResponse\x124\n" +
	"\vRecordEvent\x12\x11.mab.EventRequest\x1a\x12.mab.EventResponse\x120\n" +
	"\tSyncState\x12\x10.mab.SyncRequest\x1a\x11.mab.SyncResponseB\x11Z\x0fpaw/internal/pbb\x06proto3"

var (
	file_mab_proto_rawDescOnce sync.Once
	file_mab_proto_rawDescData []byte
)

func file_mab_proto_rawDescGZIP() []byte {
	file_mab_proto_rawDescOnce.Do(func() {
		file_mab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mab_proto_rawDesc), len(file_mab_proto_rawDesc)))
	})
	return file_mab_proto_rawDescData
}

var file_mab_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mab_proto_goTypes = []any{
	(*DecisionRequest)(nil),  // 0: mab.DecisionRequest
	(*DecisionResponse)(nil), // 1: mab.DecisionResponse
	(*EventRequest)(nil),     // 2: mab.EventRequest
	(*EventResponse)(nil),    // 3: mab.EventResponse
	(*SyncRequest)(nil),      // 4: mab.SyncRequest
	(*SyncResponse)(nil),     // 5: mab.SyncResponse
	nil,                      // 6: mab.SyncRequest.ImpressionsEntry
	nil,                      // 7: mab.SyncRequest.ClicksEntry
}
var file_mab_proto_depIdxs = []int32{
	6, // 0: mab.SyncRequest.impressions:type_name -> mab.SyncRequest.ImpressionsEntry
	7, // 1: mab.SyncRequest.clicks:type_name -> mab.SyncRequest.ClicksEntry
	0, // 2: mab.MabEngine.GetNextAd:input_type -> mab.DecisionRequest
	2, // 3: mab.MabEngine.RecordEvent:input_type -> mab.EventRequest
	4, // 4: mab.MabEngine.SyncState:input_type -> mab.SyncRequest
	1, // 5: mab.MabEngine.GetNextAd:output_type -> mab.DecisionResponse
	3, // 6: mab.MabEngine.RecordEvent:output_type -> mab.EventResponse
	5, // 7: mab.MabEngine.SyncState:output_type -> mab.SyncResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mab_proto_init() }
func file_mab_proto_init() {
	if File_mab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mab_proto_rawDesc), len(file_mab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mab_proto_goTypes,
		DependencyIndexes: file_mab_proto_depIdxs,
		MessageInfos:      file_mab_proto_msgTypes,
	}.Build()
	File_mab_proto = out.File
	file_mab_proto_goTypes = nil
	file_mab_proto_depIdxs = nil
}
