// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: mab.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecisionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CampaignId     string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	UserContext    string                 `protobuf:"bytes,2,opt,name=user_context,json=userContext,proto3" json:"user_context,omitempty"`
	AvailableAdIds []string               `protobuf:"bytes,3,rep,name=available_ad_ids,json=availableAdIds,proto3" json:"available_ad_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	mi := &file_mab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_mab_proto_rawDescGZIP(), []int{0}
}

func (x *DecisionRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *DecisionRequest) GetUserContext() string {
	if x != nil {
		return x.UserContext
	}
	return ""
}

func (x *DecisionRequest) GetAvailableAdIds() []string {
	if x != nil {
		return x.AvailableAdIds
	}
	return nil
}

type DecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SelectedAdId  string                 `protobuf:"bytes,1,opt,name=selected_ad_id,json=selectedAdId,proto3" json:"selected_ad_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	mi := &file_mab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_mab_proto_rawDescGZIP(), []int{1}
}

func (x *DecisionResponse) GetSelectedAdId() string {
	if x != nil {
		return x.SelectedAdId
	}
	return ""
}

var File_mab_proto protoreflect.FileDescriptor

const file_mab_proto_rawDesc = "" +
	"\n" +
	"\tmab.proto\x12\x03mab\"\x7f\n" +
	"\x0fDecisionRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12!\n" +
	"\fuser_context\x18\x02 \x01(\tR\vuserContext\x12(\n" +
	"\x10available_ad_ids\x18\x03 \x03(\tR\x0eavailableAdIds\"8\n" +
	"\x10DecisionResponse\x12$\n" +
	"\x0eselected_ad_id\x18\x01 \x01(\tR\fselectedAdId2E\n" +
	"\tMabEngine\x128\n" +
	"\tGetNextAd\x12\x14.mab.DecisionRequest\x1a\x15.mab.DecisionResponseB\x11Z\x0fpaw/internal/pbb\x06proto3"

var (
	file_mab_proto_rawDescOnce sync.Once
	file_mab_proto_rawDescData []byte
)

func file_mab_proto_rawDescGZIP() []byte {
	file_mab_proto_rawDescOnce.Do(func() {
		file_mab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mab_proto_rawDesc), len(file_mab_proto_rawDesc)))
	})
	return file_mab_proto_rawDescData
}

var file_mab_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mab_proto_goTypes = []any{
	(*DecisionRequest)(nil),  // 0: mab.DecisionRequest
	(*DecisionResponse)(nil), // 1: mab.DecisionResponse
}
var file_mab_proto_depIdxs = []int32{
	0, // 0: mab.MabEngine.GetNextAd:input_type -> mab.DecisionRequest
	1, // 1: mab.MabEngine.GetNextAd:output_type -> mab.DecisionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mab_proto_init() }
func file_mab_proto_init() {
	if File_mab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mab_proto_rawDesc), len(file_mab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mab_proto_goTypes,
		DependencyIndexes: file_mab_proto_depIdxs,
		MessageInfos:      file_mab_proto_msgTypes,
	}.Build()
	File_mab_proto = out.File
	file_mab_proto_goTypes = nil
	file_mab_proto_depIdxs = nil
}
