// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: mab.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MabEngine_GetNextAd_FullMethodName = "/mab.MabEngine/GetNextAd"
)

// MabEngineClient is the client API for MabEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MabEngineClient interface {
	GetNextAd(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error)
}

type mabEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewMabEngineClient(cc grpc.ClientConnInterface) MabEngineClient {
	return &mabEngineClient{cc}
}

func (c *mabEngineClient) GetNextAd(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionResponse)
	err := c.cc.Invoke(ctx, MabEngine_GetNextAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MabEngineServer is the server API for MabEngine service.
// All implementations must embed UnimplementedMabEngineServer
// for forward compatibility.
type MabEngineServer interface {
	GetNextAd(context.Context, *DecisionRequest) (*DecisionResponse, error)
	mustEmbedUnimplementedMabEngineServer()
}

// UnimplementedMabEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMabEngineServer struct{}

func (UnimplementedMabEngineServer) GetNextAd(context.Context, *DecisionRequest) (*DecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNextAd not implemented")
}
func (UnimplementedMabEngineServer) mustEmbedUnimplementedMabEngineServer() {}
func (UnimplementedMabEngineServer) testEmbeddedByValue()                   {}

// UnsafeMabEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MabEngineServer will
// result in compilation errors.
type UnsafeMabEngineServer interface {
	mustEmbedUnimplementedMabEngineServer()
}

func RegisterMabEngineServer(s grpc.ServiceRegistrar, srv MabEngineServer) {
	// If the following call panics, it indicates UnimplementedMabEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MabEngine_ServiceDesc, srv)
}

func _MabEngine_GetNextAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MabEngineServer).GetNextAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MabEngine_GetNextAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MabEngineServer).GetNextAd(ctx, req.(*DecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MabEngine_ServiceDesc is the grpc.ServiceDesc for MabEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MabEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mab.MabEngine",
	HandlerType: (*MabEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNextAd",
			Handler:    _MabEngine_GetNextAd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mab.proto",
}
