# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mab.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'mab.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmab.proto\x12\x03mab\"V\n\x0f\x44\x65\x63isionRequest\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\t\x12\x14\n\x0cuser_context\x18\x02 \x01(\t\x12\x18\n\x10\x61vailable_ad_ids\x18\x03 \x03(\t\"*\n\x10\x44\x65\x63isionResponse\x12\x16\n\x0eselected_ad_id\x18\x01 \x01(\t2E\n\tMabEngine\x12\x38\n\tGetNextAd\x12\x14.mab.DecisionRequest\x1a\x15.mab.DecisionResponseB\x11Z\x0fpaw/internal/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mab_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017paw/internal/pb'
  _globals['_DECISIONREQUEST']._serialized_start=18
  _globals['_DECISIONREQUEST']._serialized_end=104
  _globals['_DECISIONRESPONSE']._serialized_start=106
  _globals['_DECISIONRESPONSE']._serialized_end=148
  _globals['_MABENGINE']._serialized_start=150
  _globals['_MABENGINE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
