# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mab_pb2 as mab__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mab_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MabEngineStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNextAd = channel.unary_unary(
                '/mab.MabEngine/GetNextAd',
                request_serializer=mab__pb2.DecisionRequest.SerializeToString,
                response_deserializer=mab__pb2.DecisionResponse.FromString,
                _registered_method=True)
        self.RecordEvent = channel.unary_unary(
                '/mab.MabEngine/RecordEvent',
                request_serializer=mab__pb2.EventRequest.SerializeToString,
                response_deserializer=mab__pb2.EventResponse.FromString,
                _registered_method=True)
        self.SyncState = channel.unary_unary(
                '/mab.MabEngine/SyncState',
                request_serializer=mab__pb2.SyncRequest.SerializeToString,
                response_deserializer=mab__pb2.SyncResponse.FromString,
                _registered_method=True)


class MabEngineServicer:
    """Missing associated documentation comment in .proto file."""

    def GetNextAd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MabEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNextAd': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextAd,
                    request_deserializer=mab__pb2.DecisionRequest.FromString,
                    response_serializer=mab__pb2.DecisionResponse.SerializeToString,
            ),
            'RecordEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordEvent,
                    request_deserializer=mab__pb2.EventRequest.FromString,
                    response_serializer=mab__pb2.EventResponse.SerializeToString,
            ),
            'SyncState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncState,
                    request_deserializer=mab__pb2.SyncRequest.FromString,
                    response_serializer=mab__pb2.SyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mab.MabEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mab.MabEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MabEngine:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNextAd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mab.MabEngine/GetNextAd',
            mab__pb2.DecisionRequest.SerializeToString,
            mab__pb2.DecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mab.MabEngine/RecordEvent',
            mab__pb2.EventRequest.SerializeToString,
            mab__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mab.MabEngine/SyncState',
            mab__pb2.SyncRequest.SerializeToString,
            mab__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
